# Conexão com o Banco de Dados (Lê do ambiente se existir, senão usa local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taskmanager_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:sua_senha_local}

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET:segredo_padrao_local_apenas_para_desenvolvimento}
jwt.expiration=${JWT_EXPIRATION:86400000}